M48
; DRILL file {KiCad (6.0.2)} date Thu Mar 17 13:32:31 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-17T13:32:31+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X123.0Y-82.0
X123.0Y-123.0
X189.0Y-82.0
X189.0Y-123.0
T0
M30
